name: fb_auth_example
description: Demonstrates how to use the fb_auth plugin.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  cupertino_icons: ^0.1.2
  fb_auth:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
